Cortex/Cortex.Web/Controllers/MainController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;

// For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860

namespace Cortex.Web.Controllers
{
    public class MainController : Controller
    {
        [HttpGet("/")]
        public IActionResult Index()
        {
            return View();
        }
    }
}

Cortex/Cortex.Web/ViewComponents/RecentNetworksViewComponent.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Cortex.Services.Dtos;
using Cortex.Services.Interfaces;
using Cortex.Web.Models.Networks;
using Microsoft.AspNetCore.Mvc;

namespace Cortex.Web.ViewComponents
{
    public class RecentNetworksViewComponent : ViewComponent
    {
        private readonly INetworkService _networkService;
        private readonly IUserService _userService;

        public RecentNetworksViewComponent(
            INetworkService networkService,
            IUserService userService)
        {
            _networkService = networkService;
            _userService = userService;
        }

        public async Task<IViewComponentResult> InvokeAsync(Guid userId)
        {
            IList<Network> networks = await _networkService.GetRecentNetworksAsync(userId);

            List<Guid> authorIds = networks.Select(n => n.OwnerId).ToList();
            Dictionary<Guid, User> authors = (await _userService.GetUsersAsync(authorIds)).ToDictionary(u => u.Id);

            List<NetworkModel> models = networks
                .Select(n => new NetworkModel(n, authors[n.OwnerId]))
                .ToList();

            return View(models);
        }
    }
}

Cortex/Cortex.Web/ViewComponents/RegistrationViewComponent.cs
using Microsoft.AspNetCore.Mvc;

namespace Cortex.Web.ViewComponents
{
    public class RegistrationViewComponent : ViewComponent
    {
        public IViewComponentResult Invoke()
        {
            return View();
        }
    }
}

Cortex/Cortex.Web/Views/Main/Index.cshtml
@using Cortex.Auth
@{
    ViewBag.Title = "Home";
    ViewBag.IsLanding = !User.Identity.IsAuthenticated;
}

@if (User.Identity.IsAuthenticated)
{
    <h2>Recent</h2>
    <div>
        @await Component.InvokeAsync("RecentNetworks", new { userId = User.GetId() })
    </div>
}
else
{
    <div class="landing">
        <div class="landing-shadow">
            <div class="landing-content">
                <div class="landing-description">
                    <h1>
                        Created for data scientists
                    </h1>
                    <h3>
                        Cortex is a neural networks diagrams editor. From researches to business, you can create and version diagrams,
                        manage neural network projects, and push data science forward alongside with other enthusiasts.
                    </h3>
                </div>
                <div class="landing-registration">
                    @await Component.InvokeAsync("Registration")
                </div>
            </div>
        </div>
    </div>
}