Cortex/Cortex.Web/Models/Networks/NetworkDetailsModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using Cortex.DomainModels;
using Cortex.Services.Dtos;
using Cortex.Web.Models.Shared;

namespace Cortex.Web.Models.Networks
{
    public class NetworkDetailsModel
    {
        public NetworkDetailsModel(
            Network network,
            Dictionary<Guid, User> users,
            bool isOwner,
            bool canEdit,
            bool hasVersions)
        {
            IsOwner = isOwner;
            Id = network.Id;
            Name = network.Name;
            Description = network.Description;
            CreatedDate = network.CreatedDate;
            Author = new UserDisplayModel(users[network.OwnerId]);
            ReadAccess = ConvertAccessModeToString(network.ReadAccess.AccessMode);
            ReadAccessUsers = network.ReadAccess.PermittedUsers
                .Select(id => new UserDisplayModel(users[id]))
                .ToList();
            WriteAccess = ConvertAccessModeToString(network.WriteAccess.AccessMode);
            WriteAccessUsers = network.WriteAccess.PermittedUsers
                .Select(id => new UserDisplayModel(users[id]))
                .ToList();
            CanEdit = canEdit;
            HasVersions = hasVersions;
        }

        public Guid Id { get; }

        public string Name { get; }

        public string Description { get; }

        public DateTimeOffset CreatedDate { get; }

        public UserDisplayModel Author { get; }

        public bool IsOwner { get; }

        public string ReadAccess { get; }

        public List<UserDisplayModel> ReadAccessUsers { get; }

        public string WriteAccess { get; }

        public List<UserDisplayModel> WriteAccessUsers { get; }

        public bool CanEdit { get; }

        public bool HasVersions { get; set; }

        private static string ConvertAccessModeToString(AccessMode mode)
        {
            switch (mode)
            {
                case AccessMode.Private:
                    return "Private";
                case AccessMode.ByPermission:
                    return "By permission";
                case AccessMode.Public:
                    return "Public";
                default:
                    throw new ArgumentOutOfRangeException(nameof(mode), mode, null);
            }
        }
    }
}

Cortex/Cortex.Web/Models/Networks/NetworkEditModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using Cortex.Services.Dtos;
using Cortex.Web.Models.Shared;
using Microsoft.AspNetCore.Mvc;

namespace Cortex.Web.Models.Networks
{
    public class NetworkEditModel
    {
        public NetworkEditModel()
        {
        }

        public NetworkEditModel(Network network, Dictionary<Guid, User> users)
        {
            Id = network.Id;
            Name = network.Name;
            Description = network.Description;
            ViewMode = (int)network.ReadAccess.AccessMode;
            ViewUsers = network.ReadAccess.PermittedUsers.Select(id => new UserDisplayModel(users[id])).ToList();
            EditMode = (int)network.WriteAccess.AccessMode;
            EditUsers = network.WriteAccess.PermittedUsers.Select(id => new UserDisplayModel(users[id])).ToList();
        }

        [HiddenInput]
        public Guid Id { get; set; }

        [MaxLength(100, ErrorMessage = "Name should be shorter than 100 symbols")]
        [Display(Name = "Name")]
        [Required]
        public string Name { get; set; }

        [MaxLength(6000, ErrorMessage = "Description should be shorter than 6000 symbols")]
        [DataType(DataType.MultilineText)]
        [Display(Name = "Description")]
        public string Description { get; set; }

        [Range(0, 2)]
        public int ViewMode { get; set; }

        [Range(0, 2)]
        public int EditMode { get; set; }

        public IList<UserDisplayModel> ViewUsers { get; set; }

        public IList<UserDisplayModel> EditUsers { get; set; }
    }
}

Cortex/Cortex.Web/Models/Networks/NetworkModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Cortex.Services.Dtos;
using Cortex.Web.Models.Shared;

namespace Cortex.Web.Models.Networks
{
    public class NetworkModel
    {
        public NetworkModel(Network network)
        {
            Id = network.Id;
            Name = network.Name;
            Description = network.Description;
            CreatedDate = network.CreatedDate;
        }

        public NetworkModel(Network network, User owner)
        {
            Id = network.Id;
            Name = network.Name;
            Description = network.Description;
            CreatedDate = network.CreatedDate;
            Author = new UserDisplayModel(owner);
        }

        public Guid Id { get; set; }

        public string Name { get; set; }

        public string Description { get; set; }

        public DateTimeOffset CreatedDate { get; set; }

        public UserDisplayModel Author { get; set; }
    }
}

Cortex/Cortex.Web/Models/Networks/NetworkUpdateModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using Cortex.Services.Dtos;
using Cortex.Web.Models.Shared;
using Microsoft.AspNetCore.Mvc;

namespace Cortex.Web.Models.Networks
{
    public class NetworkUpdateModel
    {
        public NetworkUpdateModel()
        {
        }

        public Guid Id { get; set; }

        [MaxLength(100, ErrorMessage = "Name should be shorter than 100 symbols")]
        [Required]
        public string Name { get; set; }

        [MaxLength(6000, ErrorMessage = "Description should be shorter than 6000 symbols")]
        public string Description { get; set; }

        [Range(0, 2)]
        public int ViewMode { get; set; }

        [Range(0, 2)]
        public int EditMode { get; set; }

        public IList<Guid> ViewUsers { get; set; }

        public IList<Guid> EditUsers { get; set; }
    }
}

Cortex/Cortex.Web/Models/Networks/NewNetworkModel.cs
using System.ComponentModel.DataAnnotations;

namespace Cortex.Web.Models.Networks
{
    public class NewNetworkModel
    {
        [MaxLength(100, ErrorMessage = "Name should be shorter than 100 symbols")]
        [Display(Name = "Name")]
        [Required]
        public string Name { get; set; }

        [MaxLength(6000, ErrorMessage = "Description should be shorter than 6000 symbols")]
        [DataType(DataType.MultilineText)]
        [Display(Name = "Description")]
        public string Description { get; set; }
    }
}

Cortex/Cortex.Web/Controllers/NetworkVersionsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Cortex.Auth;
using Cortex.Services.Dtos;
using Cortex.Services.Interfaces;
using Cortex.Web.Models.NetworkVersions;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace Cortex.Web.Controllers
{
    [Authorize]
    public class NetworkVersionsController : Controller
    {
        private readonly INetworkService _networkService;
        private readonly INetworkVersionsService _networkVersionsService;
        private readonly IUserService _userService;

        public NetworkVersionsController(
            INetworkService networkService,
            INetworkVersionsService networkVersionsService,
            IUserService userService)
        {
            _networkService = networkService;
            _networkVersionsService = networkVersionsService;
            _userService = userService;
        }

        [HttpGet("/network/{networkId:guid}/new-version")]
        public async Task<IActionResult> CreateVersion(Guid networkId)
        {
            bool canEdit = await _networkService.CanEditNetworkAsync(networkId, User.GetId());

            if (!canEdit)
            {
                return Forbid();
            }

            NetworkVersionMetadata currentVersion = await _networkVersionsService.GetCurrentVersionInfoAsync(networkId);
            Network network = await _networkService.GetNetworkAsync(networkId);

            var model = new NewNetworkVersionModel(network, currentVersion?.Id);

            return View(model);
        }

        [AllowAnonymous]
        [HttpGet("/network/{networkId:guid}/{versionId:guid}")]
        public async Task<IActionResult> GetVersion(Guid networkId, Guid versionId)
        {
            bool canAccess = User.Identity.IsAuthenticated
                ? await _networkService.CanAccessNetworkAsync(networkId, User.GetId())
                : await _networkService.CanAccessNetworkAnonymouslyAsync(networkId);

            if (!canAccess)
            {
                return Forbid();
            }

            NetworkVersionMetadata version = await _networkVersionsService.GetVersionInfoAsync(versionId);
            NetworkVersionMetadata currentVersion = await _networkVersionsService.GetCurrentVersionInfoAsync(networkId);
            Network network = await _networkService.GetNetworkAsync(networkId);
            User author = await _userService.GetUserAsync(version.AuthorId);
            bool canEdit = User.Identity.IsAuthenticated
                        && await _networkService.CanEditNetworkAsync(networkId, User.GetId());

            var model = new NetworkVersionDetailsModel(version, network, author, canEdit, currentVersion.Id == versionId);

            return View("GetVersion", model);
        }

        [AllowAnonymous]
        [HttpGet("/network/{networkId:guid}/current-version")]
        public async Task<IActionResult> GetCurrentVersion(Guid networkId)
        {
            NetworkVersionMetadata currentVersion = await _networkVersionsService.GetCurrentVersionInfoAsync(networkId);

            return await GetVersion(networkId, currentVersion.Id);
        }

        [HttpPost("/version/{versionId:guid}/revert")]
        public async Task<IActionResult> RevertVersion(Guid versionId)
        {
            NetworkVersionMetadata version = await _networkVersionsService.GetVersionInfoAsync(versionId);
            bool canEdit = await _networkService.CanEditNetworkAsync(version.NetworkId, User.GetId());

            if (!canEdit)
            {
                return Forbid();
            }

            await _networkVersionsService.RevertVersionAsync(versionId, User.GetId());

            return RedirectToAction(nameof(NetworksController.GetNetwork), "Networks", new { id = version.NetworkId });
        }

        [HttpPost("/version/{versionId:guid}/reset")]
        public async Task<IActionResult> ResetToVersion(Guid versionId)
        {
            NetworkVersionMetadata version = await _networkVersionsService.GetVersionInfoAsync(versionId);
            bool canEdit = await _networkService.CanEditNetworkAsync(version.NetworkId, User.GetId());

            if (!canEdit)
            {
                return Forbid();
            }

            await _networkVersionsService.ResetToVersionAsync(versionId);

            return RedirectToAction(nameof(NetworksController.GetNetwork), "Networks", new { id = version.NetworkId });
        }
    }
}

Cortex/Cortex.Web/Controllers/NetworksController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Cortex.Auth;
using Cortex.Services.Dtos;
using Cortex.Services.Interfaces;
using Cortex.Web.Models.Networks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace Cortex.Web.Controllers
{
    [Authorize]
    public class NetworksController : Controller
    {
        private readonly INetworkService _networkService;
        private readonly INetworkVersionsService _networkVersionsService;
        private readonly IUserService _userService;

        public NetworksController(INetworkService networkService, INetworkVersionsService networkVersionsService, IUserService userService)
        {
            _networkService = networkService;
            _networkVersionsService = networkVersionsService;
            _userService = userService;
        }

        [HttpGet("/create-network")]
        public IActionResult CreateNetwork()
        {
            return View();
        }

        [HttpPost("/create-network")]
        public async Task<IActionResult> CreateNetwork(NewNetworkModel model)
        {
            if (!ModelState.IsValid)
            {
                return View();
            }

            var network = new NewNetwork
            {
                Name = model.Name,
                Description = model.Description,
                OwnerId = User.GetId()
            };

            Guid networkId = await _networkService.CreateNetworkAsync(network);

            return RedirectToAction(nameof(GetNetwork), 
                new
                {
                    id = networkId
                });
        }

        [HttpGet("/networks/{id:guid}")]
        [AllowAnonymous]
        public async Task<IActionResult> GetNetwork(Guid id)
        {
            bool canAccess = User.Identity.IsAuthenticated
                ? await _networkService.CanAccessNetworkAsync(id, User.GetId())
                : await _networkService.CanAccessNetworkAnonymouslyAsync(id);

            if (!canAccess)
            {
                return Forbid();
            }

            Network network = await _networkService.GetNetworkAsync(id);
            List<Guid> networkUserIds = network.ReadAccess.PermittedUsers
                .Union(network.WriteAccess.PermittedUsers)
                .Union(Enumerable.Repeat(network.OwnerId, 1))
                .ToList();

            Dictionary<Guid, User> users = (await _userService.GetUsersAsync(networkUserIds)).ToDictionary(u => u.Id);

            bool isOwner = false;
            bool canEdit = false;

            if (User.Identity.IsAuthenticated)
            {
                Guid userId = User.GetId();

                isOwner = userId == network.OwnerId;
                canEdit = User.Identity.IsAuthenticated
                       && await _networkService.CanEditNetworkAsync(id, userId);
            }

            NetworkVersionMetadata currentVersion = await _networkVersionsService.GetCurrentVersionInfoAsync(id);

            var model = new NetworkDetailsModel(network, users, isOwner, canEdit, currentVersion != null);

            return View(model);
        }

        [HttpGet("/networks")]
        public async Task<IActionResult> GetOwnNetworks()
        {
            IList<Network> networks =  await _networkService.GetUserNetworksAsync(User.GetId());

            List<NetworkModel> models = networks
                .Select(n => new NetworkModel(n))
                .OrderBy(n => n.Name)
                .ToList();

            return View(models);
        }

        [HttpGet("/networks/shared")]
        public async Task<IActionResult> GetSharedNetworks()
        {
            IList<Network> networks = await _networkService.GetUserSharedNetworksAsync(User.GetId());

            List<Guid> authorIds = networks.Select(n => n.OwnerId).ToList();
            Dictionary<Guid, User> authors = (await _userService.GetUsersAsync(authorIds)).ToDictionary(u => u.Id);

            List<NetworkModel> models = networks
                .Select(n => new NetworkModel(n, authors[n.OwnerId]))
                .OrderBy(n => n.Name)
                .ToList();

            return View(models);
        }

        [HttpGet("/networks/{id:guid}/edit")]
        public async Task<IActionResult> EditNetwork(Guid id)
        {
            Network network = await _networkService.GetNetworkAsync(id);

            if (network.OwnerId != User.GetId())
            {
                return Forbid();
            }

            List<Guid> permittedUserIds = network.ReadAccess.PermittedUsers
                .Concat(network.WriteAccess.PermittedUsers)
                .Distinct()
                .ToList();

            IList<User> permittedUsers = await _userService.GetUsersAsync(permittedUserIds);

            Dictionary<Guid, User> usersMapping = permittedUsers.ToDictionary(u => u.Id);

            var model = new NetworkEditModel(network, usersMapping);

            return View(model);
        }

        [HttpPost("/networks/edit")]
        public async Task<IActionResult> Edit(NetworkUpdateModel model)
        {
            if (!ModelState.IsValid)
            {
                return await EditNetwork(model.Id);
            }

            Network network = await _networkService.GetNetworkAsync(model.Id);

            if (network.OwnerId != User.GetId())
            {
                return Forbid();
            }

            var networkUpdate = new NetworkUpdate(
                model.Name,
                model.Description,
                model.ViewMode,
                model.EditMode,
                model.ViewUsers ?? new List<Guid>(),
                model.EditUsers ?? new List<Guid>());

            await _networkService.UpdateNetworkAsync(model.Id, networkUpdate);

            return RedirectToAction("GetNetwork", "Networks", new { network.Id });
        }
    }
}

Cortex/Cortex.Web/Views/Networks/CreateNetwork.cshtml
@using Cortex.Web.Models.Networks
@model NewNetworkModel

@{
    ViewBag.Title = "New Network";
}

<h2>New network</h2>

<form class="form" method="post" data-validate="" asp-controller="Networks" asp-action="CreateNetwork">
    <div class="form-row">
        <label asp-for="Name"></label>
        <input id="name-input" required="" maxlength="100" asp-for="Name" />
    </div>
    <div class="form-row">
        <label class="top-label" asp-for="Description"></label>
        <textarea id="description-input" rows="5" maxlength="6000" asp-for="Description"></textarea>
    </div>
    <button type="submit" class="button-primary">Save</button>
</form>

Cortex/Cortex.Web/Views/Networks/EditNetwork.cshtml
@using Cortex.Web.Models.Shared
@model Cortex.Web.Models.Networks.NetworkEditModel

@{
    ViewBag.Title = $"Edit {Model.Name}";
}

<h2>Edit network</h2>

<form class="form" method="post" data-validate="" asp-controller="Networks" asp-action="Edit">
    <input asp-for="Id" />
    <div class="form-row">
        <label asp-for="Name"></label>
        <input id="name-input" required="" maxlength="100" asp-for="Name" />
    </div>
    <div class="form-row">
        <label class="top-label" asp-for="Description"></label>
        <textarea id="description-input" rows="5" maxlength="6000" asp-for="Description"></textarea>
    </div>

    <div class="form-row">
        <label class="top-label">Access</label>
        <div class="hidden" id="view-users">
            @foreach (UserDisplayModel user in Model.ViewUsers)
            {
                <div data-id="@user.Id" data-user-name="@user.UserName.ToLower()" data-name="@user.Name"></div>
            }
        </div>
        <div class="hidden" id="edit-users">
            @foreach (UserDisplayModel user in Model.EditUsers)
            {
                <div data-id="@user.Id" data-user-name="@user.UserName.ToLower()" data-name="@user.Name"></div>
            }
        </div>
        <div class="editor" 
             id="access-editor"
             data-view-mode="@Model.ViewMode"
             data-edit-mode="@Model.EditMode"
             data-view-users-id="view-users"
             data-edit-users-id="edit-users"></div>
    </div>

    <div class="buttons-section">
        <a class="button-light" asp-controller="Networks" asp-action="GetNetwork" asp-route-id="@Model.Id">Cancel</a>
        <button type="submit" class="button-primary">Save</button>
    </div>
</form>

Cortex/Cortex.Web/Views/Networks/GetNetwork.cshtml
@using Cortex.Auth
@using Cortex.Web.Models.Shared
@model Cortex.Web.Models.Networks.NetworkDetailsModel

@{
    ViewBag.Title = Model.Name;
}

<div class="heading">
    <span class="fs-2">@Model.Name</span>
    @if (Model.IsOwner)
    {
        <a class="button-primary button-small" asp-controller="Networks" asp-action="EditNetwork" asp-route-id="@Model.Id">
            <i class="fa fa-edit"></i>
            <span>Edit</span>
        </a>
    }
    @if (Model.HasVersions)
    {
        <a class="button-primary button-small" asp-controller="NetworkVersions" asp-action="GetCurrentVersion" asp-route-networkId="@Model.Id">
            <i class="fa fa-eye"></i>
            <span>View</span>
        </a>
    }
</div>

<small>
    <span>by</span>
    @Html.DisplayForUser(Model.Author, User.GetNullableId())
    <time datetime="@Model.CreatedDate.ToString("o")" data-local></time>
</small>

@if (Model.IsOwner)
{
    <div class="section">
        <h4>Access</h4>
        <div class="grid">
            <div class="grid-row">
                <span class="label-cell">View</span>
                <div class="cell">
                    <span>@Model.ReadAccess</span>
                    @if (Model.ReadAccessUsers.Any())
                    {
                        string users = String.Join(", ", Model.ReadAccessUsers.Select(u => $"{u.Name} <{u.UserName.ToLower()}>"));

                        <span>(@users)</span>
                    }
                </div>
            </div>
            <div class="grid-row">
                <span class="label-cell">Edit</span>
                <div class="cell">
                    <span>@Model.WriteAccess</span>
                    @if (Model.WriteAccessUsers.Any())
                    {
                        string users = String.Join(", ", Model.WriteAccessUsers.Select(u => $"{u.Name} <{u.UserName.ToLower()}>"));

                        <span>(@users)</span>
                    }
                </div>
            </div>
        </div>
    </div>
}

<div class="section">
    <h4>Description</h4>
    @if (String.IsNullOrEmpty(Model.Description))
    {
        <div class="empty-text">
            No description
        </div>
    }
    else
    {
        <div>
            @Model.Description
        </div>
    }
</div>

<div class="section">
    <div class="section-heading">
        <h4>Versions</h4>
        @if (Model.CanEdit)
        {
            <a class="button-primary button-small"
               asp-controller="NetworkVersions"
               asp-action="CreateVersion"
               asp-route-networkId="@Model.Id">
                <i class="fa fa-plus"></i>
                <span>Add</span>
            </a>
        }
    </div>
    <div>
        @await Component.InvokeAsync("NetworkVersions", new { networkId = Model.Id, userId = User.GetNullableId() })
    </div>
</div>

Cortex/Cortex.Web/Views/Networks/GetOwnNetworks.cshtml
@using Cortex.Web.Models.Networks
@model List<NetworkModel>

@{
    ViewBag.Title = "Your networks";
}

<h2>Your networks</h2>

@if (Model.Count > 0)
{
    <div class="networks-list">
        @foreach (NetworkModel network in Model)
        {
            <div class="list-item-container">
                <div class="list-item-heading">
                    <a class="fs-3" asp-controller="Networks" asp-action="GetNetwork" asp-route-id="@network.Id">
                        @network.Name
                    </a>
                    <small>
                        <time datetime="@network.CreatedDate.ToString("o")" data-local></time>
                    </small>
                </div>
                @if (String.IsNullOrEmpty(network.Description))
                {
                    <p class="empty-text">
                        No description
                    </p>
                }
                else
                {
                    <p class="truncated-text" title="@network.Description">@network.Description</p>
                }
            </div>
        }
    </div>
}
else
{
    <p>
        You have no networks yet. <a asp-controller="Networks" asp-action="CreateNetwork">Create new network</a>.
    </p>
}

Cortex/Cortex.Web/Views/Networks/GetSharedNetworks.cshtml
@using Cortex.Auth
@using Cortex.Web.Models.Networks
@model List<NetworkModel>

@{
    ViewBag.Title = "Shared networks";
}

<h2>Shared with you</h2>

@if (Model.Count > 0)
{
    <div class="networks-list">
        @foreach (NetworkModel network in Model)
        {
            <div class="list-item-container">
                <div class="list-item-heading">
                    <a class="fs-3" asp-controller="Networks" asp-action="GetNetwork" asp-route-id="@network.Id">
                        @network.Name
                    </a>
                    <small>
                        <span>by</span>
                        @Html.DisplayForUser(network.Author, User.GetNullableId())
                        <time datetime="@network.CreatedDate.ToString("o")" data-local></time>
                    </small>
                </div>

                @if (String.IsNullOrEmpty(network.Description))
                {
                    <p class="empty-text">
                        No description
                    </p>
                }
                else
                {
                    <p class="truncated-text" title="@network.Description">@network.Description</p>
                }
            </div>
        }
    </div>
}
else
{
    <p>
        No shared networks.
    </p>
}